const questions = [
  {
    id: 1,
    sentence: "Tu ______ une pomme.",
    verb: "manger",
    subject: "Tu",
    fullPrompt: "Tu (manger) ______ une pomme.",
    correctAnswer: "as mangé",
    acceptedAnswers: ["as mangé", "as mange"],
    options: ["as mangé", "a mangé", "avez mangé", "es mangé"],
    completedSentence: "Tu as mangé une pomme.",
    translation: "You ate an apple.",
    rule: "Passé composé with AVOIR: Tu as + mangé (ER verb -> é)"
  },
  {
    id: 2,
    sentence: "Elle ______ son travail.",
    verb: "finir",
    subject: "Elle",
    fullPrompt: "Elle (finir) ______ son travail.",
    correctAnswer: "a fini",
    acceptedAnswers: ["a fini"],
    options: ["a fini", "as fini", "est finie", "ont fini"],
    completedSentence: "Elle a fini son travail.",
    translation: "She finished her work.",
    rule: "Passé composé with AVOIR: Elle a + fini (IR verb -> i)"
  },
  {
    id: 3,
    sentence: "Nous ______ nos devoirs.",
    verb: "faire",
    subject: "Nous",
    fullPrompt: "Nous (faire) ______ nos devoirs.",
    correctAnswer: "avons fait",
    acceptedAnswers: ["avons fait"],
    options: ["avons fait", "avez fait", "sommes faits", "ont fait"],
    completedSentence: "Nous avons fait nos devoirs.",
    translation: "We did our homework.",
    rule: "Passé composé with AVOIR: Nous avons + fait (Irregular participle)"
  },
  {
    id: 4,
    sentence: "Ils ______ le train.",
    verb: "prendre",
    subject: "Ils",
    fullPrompt: "Ils (prendre) ______ le train.",
    correctAnswer: "ont pris",
    acceptedAnswers: ["ont pris"],
    options: ["ont pris", "sont pris", "avez pris", "ont prendu"],
    completedSentence: "Ils ont pris le train.",
    translation: "They took the train.",
    rule: "Passé composé with AVOIR: Ils ont + pris (Irregular participle)"
  },
  {
    id: 5,
    sentence: "Vous ______ le livre.",
    verb: "lire",
    subject: "Vous",
    fullPrompt: "Vous (lire) ______ le livre.",
    correctAnswer: "avez lu",
    acceptedAnswers: ["avez lu"],
    options: ["avez lu", "avons lu", "êtes lus", "a lu"],
    completedSentence: "Vous avez lu le livre.",
    translation: "You read the book.",
    rule: "Passé composé with AVOIR: Vous avez + lu (Irregular participle)"
  },
  {
    id: 6,
    sentence: "Il ______ une lettre.",
    verb: "écrire",
    subject: "Il",
    fullPrompt: "Il (écrire) ______ une lettre.",
    correctAnswer: "a écrit",
    acceptedAnswers: ["a écrit", "a ecrit"],
    options: ["a écrit", "est écrit", "as écrit", "a écris"],
    completedSentence: "Il a écrit une lettre.",
    translation: "He wrote a letter.",
    rule: "Passé composé with AVOIR: Il a + écrit (Irregular participle)"
  },
  {
    id: 7,
    sentence: "J’______ un nouveau sac.",
    verb: "acheter",
    subject: "J’",
    fullPrompt: "J’(acheter) ______ un nouveau sac.",
    correctAnswer: "ai acheté",
    acceptedAnswers: ["ai acheté", "ai achete"],
    options: ["ai acheté", "a acheté", "suis acheté", "avons acheté"],
    completedSentence: "J’ai acheté un nouveau sac.",
    translation: "I bought a new bag.",
    rule: "Passé composé with AVOIR: J'ai + acheté (ER verb -> é)"
  },
  {
    id: 8,
    sentence: "Tu ______ du lait.",
    verb: "boire",
    subject: "Tu",
    fullPrompt: "Tu (boire) ______ du lait.",
    correctAnswer: "as bu",
    acceptedAnswers: ["as bu"],
    options: ["as bu", "a bu", "es bu", "avez bu"],
    completedSentence: "Tu as bu du lait.",
    translation: "You drank some milk.",
    rule: "Passé composé with AVOIR: Tu as + bu (Irregular participle)"
  },
  {
    id: 9,
    sentence: "Elle ______ un film.",
    verb: "voir",
    subject: "Elle",
    fullPrompt: "Elle (voir) ______ un film.",
    correctAnswer: "a vu",
    acceptedAnswers: ["a vu"],
    options: ["a vu", "est vue", "as vu", "a voyé"],
    completedSentence: "Elle a vu un film.",
    translation: "She saw a movie.",
    rule: "Passé composé with AVOIR: Elle a + vu (Irregular participle)"
  },
  {
    id: 10,
    sentence: "Nous ______ au football.",
    verb: "jouer",
    subject: "Nous",
    fullPrompt: "Nous (jouer) ______ au football.",
    correctAnswer: "avons joué",
    acceptedAnswers: ["avons joué", "avons joue"],
    options: ["avons joué", "sommes joués", "avez joué", "ont joué"],
    completedSentence: "Nous avons joué au football.",
    translation: "We played football (soccer).",
    rule: "Passé composé with AVOIR: Nous avons + joué (ER verb -> é)"
  },
  {
    id: 11,
    sentence: "Vous ______ un examen.",
    verb: "avoir",
    subject: "Vous",
    fullPrompt: "Vous (avoir) ______ un examen.",
    correctAnswer: "avez eu",
    acceptedAnswers: ["avez eu"],
    options: ["avez eu", "êtes eus", "avons eu", "ont eu"],
    completedSentence: "Vous avez eu un examen.",
    translation: "You had an exam.",
    rule: "Passé composé of AVOIR: Vous avez + eu"
  },
  {
    id: 12,
    sentence: "Ils ______ très heureux.",
    verb: "être",
    subject: "Ils",
    fullPrompt: "Ils (être) ______ très heureux.",
    correctAnswer: "ont été",
    acceptedAnswers: ["ont été", "ont ete"],
    options: ["ont été", "sont étés", "avez été", "ont étés"],
    completedSentence: "Ils ont été très heureux.",
    translation: "They were very happy.",
    rule: "Passé composé of ÊTRE: Ils ont + été (uses auxiliary Avoir!)"
  },
  {
    id: 13,
    sentence: "Je ______ au cinéma.",
    verb: "aller",
    subject: "Je",
    fullPrompt: "Je (aller) ______ au cinéma.",
    correctAnswer: "suis allé(e)",
    acceptedAnswers: ["suis allé", "suis allée", "suis allé(e)", "suis alle", "suis allee"],
    options: ["suis allé(e)", "ai allé", "es allé", "a allé"],
    completedSentence: "Je suis allé(e) au cinéma.",
    translation: "I went to the cinema.",
    rule: "Passé composé with ÊTRE (movement verb): Je suis + allé(e)"
  },
  {
    id: 14,
    sentence: "Elle ______ chez moi.",
    verb: "venir",
    subject: "Elle",
    fullPrompt: "Elle (venir) ______ chez moi.",
    correctAnswer: "est venue",
    acceptedAnswers: ["est venue"],
    options: ["est venue", "a venu", "est venu", "a venue"],
    completedSentence: "Elle est venue chez moi.",
    translation: "She came to my place.",
    rule: "Passé composé with ÊTRE: Elle est + venue (agreement with feminine subject)"
  },
  {
    id: 15,
    sentence: "Nous ______ à Paris.",
    verb: "arriver",
    subject: "Nous",
    fullPrompt: "Nous (arriver) ______ à Paris.",
    correctAnswer: "sommes arrivé(e)s",
    acceptedAnswers: ["sommes arrivés", "sommes arrivées", "sommes arrivé(e)s", "sommes arrives", "sommes arrivees"],
    options: ["sommes arrivé(e)s", "avons arrivé", "sommes arrivés", "avez arrivé"],
    completedSentence: "Nous sommes arrivé(e)s à Paris.",
    translation: "We arrived in Paris.",
    rule: "Passé composé with ÊTRE: Nous sommes + arrivé(e)s (agreement with plural subject)"
  },
  {
    id: 16,
    sentence: "Il ______ à huit heures.",
    verb: "partir",
    subject: "Il",
    fullPrompt: "Il (partir) ______ à huit heures.",
    correctAnswer: "est parti",
    acceptedAnswers: ["est parti"],
    options: ["est parti", "a parti", "est partie", "a parté"],
    completedSentence: "Il est parti à huit heures.",
    translation: "He left at eight o'clock.",
    rule: "Passé composé with ÊTRE: Il est + parti (movement verb)"
  },
  {
    id: 17,
    sentence: "Tu ______ pendant deux heures.",
    verb: "dormir",
    subject: "Tu",
    fullPrompt: "Tu (dormir) ______ pendant deux heures.",
    correctAnswer: "as dormi",
    acceptedAnswers: ["as dormi"],
    options: ["as dormi", "es dormi", "a dormi", "as dormé"],
    completedSentence: "Tu as dormi pendant deux heures.",
    translation: "You slept for two hours.",
    rule: "Passé composé with AVOIR: Tu as + dormi"
  },
  {
    id: 18,
    sentence: "Ils ______ dans le parc.",
    verb: "courir",
    subject: "Ils",
    fullPrompt: "Ils (courir) ______ dans le parc.",
    correctAnswer: "ont couru",
    acceptedAnswers: ["ont couru"],
    options: ["ont couru", "sont courus", "ont couri", "avez couru"],
    completedSentence: "Ils ont couru dans le parc.",
    translation: "They ran in the park.",
    rule: "Passé composé with AVOIR: Ils ont + couru"
  },
  {
    id: 19,
    sentence: "Elle ______ en France.",
    verb: "naître",
    subject: "Elle",
    fullPrompt: "Elle (naître) ______ en France.",
    correctAnswer: "est née",
    acceptedAnswers: ["est née", "est nee"],
    options: ["est née", "a né", "est né", "a naît"],
    completedSentence: "Elle est née en France.",
    translation: "She was born in France.",
    rule: "Passé composé with ÊTRE: Elle est + née (feminine agreement)"
  },
  {
    id: 20,
    sentence: "Nous ______ la télévision.",
    verb: "regarder",
    subject: "Nous",
    fullPrompt: "Nous (regarder) ______ la télévision.",
    correctAnswer: "avons regardé",
    acceptedAnswers: ["avons regardé", "avons regarde"],
    options: ["avons regardé", "sommes regardés", "avez regardé", "ont regardé"],
    completedSentence: "Nous avons regardé la télévision.",
    translation: "We watched television.",
    rule: "Passé composé with AVOIR: Nous avons + regardé (ER verb -> é)"
  }
];

module.exports = questions;
